Repository FE13-Part4-Team2/Coworkers, pull requests merged in 2025-04, with the labels that each got.

#8 [chore] merge main into dev
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  .github/workflows/assign_reviewers.yml
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  .gitignore
Labels: ⚙️ chore

#19 [chore] merge main into dev
  .github/workflows/deploy.yml
  build.sh
Labels: ⚙️ chore

#31 [chore] #28/디렉토리 구조 설정
  public/icon/close.svg
  public/logo/logo_large.svg
  public/logo/logo_small.svg
  public/page/close copy.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/oauth/login/[kakao]/page.tsx
  src/app/(auth)/oauth/signup/[kakao]/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(board)/article/[articleid]/page.tsx
  src/app/(board)/article/addarticle/page.tsx
  src/app/(board)/boards/page.tsx
  src/app/(team)/add-team/page.tsx
  src/app/(team)/join-team/page.tsx
  src/app/(team)/no-team/page.tsx
  src/app/(team)/team/[teamid]/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/edit/page.tsx
  src/app/(team)/team/[teamid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/app/(user)/myhistory/page.tsx
  src/app/(user)/mypage/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/temp.ts
  src/constants/temp.ts
  src/hooks/temp.ts
  src/lib/apis/temp.ts
  src/store/temp.ts
  src/types/temp.ts
  src/utils/temp.ts
Labels: ⚙️ chore

#43 [Chore] #42/공통 컴포넌트 폴더 구조 개선
  src/components/common/Button/index.tsx
  src/components/common/DropDown/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Icons/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Toast/index.tsx
Labels: ⚙️ chore

#49 [chore] #47 랜덤 리뷰어 멤버 추가
  .github/workflows/assign_reviewers.yml
Labels: ⚙️ chore

#60 [feat] #53 fetcher 함수 생성
  package-lock.json
  package.json
  src/app/(team)/team/[teamid]/tasklist/_components/CreateTeamButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DeleteTeamButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/LoginButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/LogoutButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TeamInfo.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/lib/apis/article.ts
  src/lib/apis/articleComment.ts
  src/lib/apis/auth.ts
  src/lib/apis/comment.ts
  src/lib/apis/group.ts
  src/lib/apis/image.ts
  src/lib/apis/oAuth.ts
  src/lib/apis/recurring.ts
  src/lib/apis/task.ts
  src/lib/apis/taskList.ts
  src/lib/apis/types/article.ts
  src/lib/apis/types/articleComment.ts
  src/lib/apis/types/auth.ts
  src/lib/apis/types/comments.ts
  src/lib/apis/types/group.ts
  src/lib/apis/types/image.ts
  src/lib/apis/types/oAuth.ts
  src/lib/apis/types/recurring.ts
  src/lib/apis/types/task.ts
  src/lib/apis/types/taskList.ts
  src/lib/apis/types/user.ts
  src/lib/apis/user.ts
  src/lib/fetcher.ts
  src/lib/getNewAccessToken.ts
Labels: 💫feat

#65 [style] css 파일 카테고리별 분리, 기본 text 색상과 button cursor 스타일 지정
  src/app/layout.tsx
  src/app/styles/breakpoint.css
  src/app/styles/color.css
  src/app/styles/globals.css
  src/app/styles/text.css
  src/app/styles/toast.css
Labels: 👨🏻‍💻 style

#67 [design] #66 toast: 커스텀토스트컨테이너 리네이밍 & 토스트 디자인 변경
  src/app/layout.tsx
  src/app/styles/toast.css
  src/components/common/ToastStyle.tsx
Labels: 🎨 design

#70 [feat, chore] #61 팀, 할 일 관련 API 작업 완료
  .vscode/settings.json
  src/app/(team)/team/[teamid]/tasklist/_components/CreateTeamButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DeleteTeamButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/LoginButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TeamInfo.tsx
  src/lib/api/group/index.ts
  src/lib/api/group/type.ts
  src/lib/api/task/index.ts
  src/lib/api/task/type.ts
  src/lib/api/taskList/index.ts
  src/lib/api/taskList/type.ts
  src/lib/api/user/index.ts
  src/lib/api/user/types.ts
  src/lib/apis/article/index.ts
  src/lib/apis/article/type.ts
  src/lib/apis/articleComment/index.ts
  src/lib/apis/articleComment/type.ts
  src/lib/apis/auth/index.ts
  src/lib/apis/auth/type.ts
  src/lib/apis/comment/index.ts
  src/lib/apis/comment/type.ts
  src/lib/apis/group/index.ts
  src/lib/apis/group/type.ts
  src/lib/apis/image/index.ts
  src/lib/apis/image/type.ts
  src/lib/apis/task/index.ts
  src/lib/apis/task/type.ts
  src/lib/apis/taskList/index.ts
  src/lib/apis/taskList/type.ts
  src/lib/apis/user/index.ts
  src/lib/apis/user/types.ts
  src/lib/fetcher.ts
Labels: 💫feat, ⚙️ chore

#74 Feat/#63/icon component
  next.config.mjs
  package-lock.json
  package.json
  src/assets/icons/alert.svg
  src/assets/icons/calendar.svg
  src/assets/icons/check.svg
  src/assets/icons/check_green.svg
  src/assets/icons/check_white.svg
  src/assets/icons/checkbox_default.svg
  src/assets/icons/chekcbox_active.svg
  src/assets/icons/comment.svg
  src/assets/icons/coworkers.svg
  src/assets/icons/done.svg
  src/assets/icons/gear.svg
  src/assets/icons/gnb_menu.svg
  src/assets/icons/img.svg
  src/assets/icons/left.svg
  src/assets/icons/list.svg
  src/assets/icons/logo.svg
  src/assets/icons/plus.svg
  src/assets/icons/profile_image.svg
  src/assets/icons/progress_done.svg
  src/assets/icons/progress_ongoing.svg
  src/assets/icons/repair.svg
  src/assets/icons/repeat.svg
  src/assets/icons/right.svg
  src/assets/icons/search.svg
  src/assets/icons/three_dots.svg
  src/assets/icons/time.svg
  src/assets/icons/toggle.svg
  src/assets/icons/user.svg
  src/assets/icons/visibility_off.svg
  src/assets/icons/visibility_on.svg
  src/assets/icons/x.svg
  src/components/common/Icons/IconRenderer.tsx
  src/components/common/Icons/index.tsx
Labels: 💫feat

#75 [feat, chore] #72 인증, 유저, 자유게시판 관련 API 작업 완료
  src/app/(team)/team/[teamid]/task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/LoginButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/ModalButton.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/layout.tsx
  src/lib/apis/article/index.ts
  src/lib/apis/article/type.ts
  src/lib/apis/articleComment/index.ts
  src/lib/apis/articleComment/type.ts
  src/lib/apis/auth/index.ts
  src/lib/apis/auth/type.ts
  src/lib/apis/comment/type.ts
  src/lib/apis/group/index.ts
  src/lib/apis/group/type.ts
  src/lib/apis/image/index.ts
  src/lib/apis/image/type.ts
  src/lib/apis/task/type.ts
  src/lib/apis/taskList/type.ts
  src/lib/apis/token.ts
  src/lib/apis/uploadImage.ts
  src/lib/apis/user/index.ts
  src/lib/apis/user/type.ts
  src/lib/apis/user/types.ts
  src/lib/fetcher.ts
Labels: 💫feat, ⚙️ chore

#76 [feat] #50 Input: 쓰임새별 Input 컴포넌트 추가 / useClosePopup 훅 추가
  src/app/styles/color.css
  src/components/common/Input/InputBase.tsx
  src/components/common/Input/InputBox.tsx
  src/components/common/Input/InputChangeInfo.tsx
  src/components/common/Input/InputSignup.tsx
  src/components/common/Input/InputToggle.tsx
  src/components/common/Input/index.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/hooks/useClosePopup.ts
  src/utils/inputValidation.ts
Labels: 💫feat

#80 [design] toast: 표시 위치, 디자인 변경
  src/app/styles/toast.css
  src/components/common/ToastStyle.tsx
Labels: 🎨 design

#82 [refactor]/#78/ apis 리팩토링
  src/app/(team)/team/[teamid]/tasklist/_components/DeleteTeamButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/LoginButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TeamInfo.tsx
  src/lib/apis/article/index.ts
  src/lib/apis/articleComment/index.ts
  src/lib/apis/auth/index.ts
  src/lib/apis/comment/index.ts
  src/lib/apis/group/index.ts
  src/lib/apis/user/index.ts
Labels: ⚒️ refactor

#81 [feat] #41 버튼 컴포넌트 생성
  package-lock.json
  package.json
  src/components/common/Button/index.tsx
  src/components/common/Button/style.ts
Labels: 💫feat

#85 Fix/#84/icon component
  src/assets/icons/arrow.svg
  src/assets/icons/arrow_top.svg
  src/assets/icons/check.svg
  src/assets/icons/check_green.svg
  src/assets/icons/checkbox_active.svg
  src/assets/icons/edit.svg
  src/assets/icons/member.svg
  src/assets/icons/right.svg
  src/assets/icons/three_dots.svg
  src/assets/icons/x.svg
  src/components/common/Icons/IconRenderer.tsx
  src/components/common/Icons/index.tsx
  src/components/common/Input/InputSignup.tsx
Labels: ⚒️ fix

#87 [feat, refactor] #86 / InputTextarea 리네이밍, 모드 추가
  src/components/common/Input/InputBox.tsx
  src/components/common/Input/InputChangeInfo.tsx
  src/components/common/Input/InputSignup.tsx
  src/components/common/Input/InputTextarea.tsx
  src/components/common/Input/InputToggle.tsx
  src/components/common/Input/index.ts
Labels: 💫feat, ⚒️ refactor

#92 [refactor] #91 / 버튼 컴포넌트 neutral 타입 추가
  src/components/common/Button/style.ts
Labels: 💫feat, ⚒️ refactor

#94 [feat] #46 모달 공통 컴포넌트
  package-lock.json
  package.json
  public/icon/close.svg
  src/app/(team)/team/[teamid]/tasklist/_components/CreateTeamButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DeleteTeamButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/ModalButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TeamInfo.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/app/layout.tsx
  src/app/styles/globals.css
  src/components/common/Modal/content/CreateTaskListModal/index.tsx
  src/components/common/Modal/content/CreateTaskModal/index.tsx
  src/components/common/Modal/content/EditTaskListModal/index.tsx
  src/components/common/Modal/content/EditTaskModal/index.tsx
  src/components/common/Modal/content/ResetPasswordLinkModal/index.tsx
  src/components/common/Modal/content/TeamMemberProfileModal/index.tsx
  src/components/common/Modal/content/TestModal.tsx
  src/components/common/Modal/content/UpdatePasswordModal/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.ts
  src/components/common/Toast/index.tsx
  src/hooks/index.ts
  src/hooks/useLockBackgroundScroll.ts
  src/store/index.ts
  src/store/useModalStore.ts
  src/utils/index.ts
Labels: 💫feat

#96 [refactor, design] #95 Modal: danger 모달 상단에 AlertIcon 표시 / Task, TaskList API 함수명 변경 및 주석 추가
  src/app/(team)/team/[teamid]/tasklist/_components/ModalButton.tsx
  src/components/common/Modal/index.tsx
  src/lib/apis/task/index.ts
  src/lib/apis/taskList/index.ts
Labels: 🎨 design, ⚒️ refactor

#101 [fix, refactor] fetcher 함수 & 토큰 재발급 함수 서버/클라이언트 컴포넌트에 맞게 분리
  src/app/(team)/team/[teamid]/task/[taskid]/_components/LoginButton.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/LogoutButton.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/ModalButton.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/Tasklists.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/lib/apis/article/index.ts
  src/lib/apis/articleComment/index.ts
  src/lib/apis/auth/index.ts
  src/lib/apis/comment/index.ts
  src/lib/apis/group/index.ts
  src/lib/apis/task/index.ts
  src/lib/apis/taskList/index.ts
  src/lib/apis/uploadImage.ts
  src/lib/apis/user/index.ts
  src/lib/client/fetcher.client.ts
  src/lib/client/token.client.ts
  src/lib/server/fetcher.server.ts
  src/lib/server/token.server.ts
Labels: ⚒️ fix, ⚒️ refactor

#106 [refactor] InputValidation: 비밀번호 유효성 검사에 특수문자 추가, 이름 제한 10자 변경
  src/utils/inputValidation.ts
Labels: ⚒️ refactor
