Repository FE13-Part4-Team2/Coworkers, pull requests merged in 2025-05, with the labels that each got.

#107 [feat] #99 할 일 목록 페이지 레이아웃 및 일부 기능 구현
  src/app/(team)/team/[teamid]/task/[taskid]/_components/ModalButton.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/task/layout.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/(..)task/[taskid]/_components/CloseButton.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/(..)task/[taskid]/_components/ExpansionButton.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/(..)task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/default.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/CreateTaskButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/CalendarButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/NextDayButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/PrevDayButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/ManageButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListMenu/TaskListMenuItem.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListMenu/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/TaskCard/TaskMenuButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/TaskCard/TitleButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/TaskCard/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/Tasklists.tsx
  src/app/(team)/team/[teamid]/tasklist/layout.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/app/styles/globals.css
  src/assets/icons/expansion.svg
  src/components/common/Icons/index.tsx
  src/components/common/Modal/content/TestModal.tsx
  src/components/common/Modal/index.tsx
  src/hooks/useClosePopup.ts
  src/utils/formatDate.ts
Labels: 💫feat

#112 [feat] #108 할 일 목록 페이지 기능 추가 & API 함수 파라미터 형식 수정
  src/app/(team)/team/[teamid]/task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/(..)task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/NextDayButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/PrevDayButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/ManageButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListMenu/TaskListMenuItem.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/TaskCard/TitleButton.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/app/dev-login/_components/LoginButton.tsx
  src/app/dev-login/_components/LogoutButton.tsx
  src/app/dev-login/page.tsx
  src/hooks/useLockBackgroundScroll.ts
  src/lib/apis/article/index.ts
  src/lib/apis/articleComment/index.ts
  src/lib/apis/auth/index.ts
  src/lib/apis/comment/index.ts
  src/lib/apis/group/index.ts
  src/lib/apis/task/index.ts
  src/lib/apis/taskList/index.ts
  src/lib/apis/user/index.ts
Labels: 💫feat

#111 [Feat] #83 드롭다운 공용 컴포넌트 생성
  src/components/common/Dropdown/DropDownItem.tsx
  src/components/common/Dropdown/DropDownMenu.tsx
  src/components/common/Dropdown/DropDownTrigger.tsx
  src/components/common/Dropdown/index.tsx
Labels: 💫feat

#118 [feat, refator, design] #109 TaskDetailPage: 할일 완료 상태에 따른 레이아웃 추가 / task, tasklist 공통 컴포넌트 생성 / DropDown 공통 컴포넌트 스타일 수정
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskDetailSection/DoneInfo.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskDetailSection/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/CreateTaskButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/ManageButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/TaskCard/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListTabs/TaskListTab.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListTabs/index.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/components/common/Dropdown/DropDownMenu.tsx
  src/components/common/Dropdown/DropDownTrigger.tsx
  src/components/common/Modal/content/EditTaskModal/index.tsx
  src/components/task/TaskMenu/TaskMenuButton.tsx
  src/components/task/TaskMenu/index.tsx
  src/components/tasklist/TaskListMenu/TaskListMenuButton.tsx
  src/components/tasklist/TaskListMenu/index.tsx
Labels: 💫feat, 🎨 design, ⚒️ refactor

#123 [feat] landing page: 반응형 디자인 및 애니메이션 구현
  package-lock.json
  package.json
  public/image/landing/landing_bottom_bg_l.png
  public/image/landing/landing_bottom_bg_m.png
  public/image/landing/landing_bottom_bg_m_01.png
  public/image/landing/landing_bottom_bg_s.png
  public/image/landing/landing_icon_check.png
  public/image/landing/landing_icon_folder.png
  public/image/landing/landing_icon_message.png
  public/image/landing/landing_light.png
  public/image/landing/landing_light_01.png
  public/image/landing/landing_light_l.png
  public/image/landing/landing_light_l_01.png
  public/image/landing/landing_light_m.png
  public/image/landing/landing_light_m_01.png
  public/image/landing/landing_light_s.png
  public/image/landing/landing_light_s_01.png
  public/image/landing/landing_mockup_invitation.png
  public/image/landing/landing_mockup_reply.png
  public/image/landing/landing_mockup_team.png
  public/image/landing/landing_top_bg_l.png
  public/image/landing/landing_top_bg_m.png
  public/image/landing/landing_top_bg_s.png
  public/image/landing/landing_top_pattern_l.png
  public/image/landing/landing_top_pattern_m.png
  public/image/landing/landing_top_pattern_s.png
  public/image/landing/runner.svg
  public/image/landing/smoke.svg
  public/image/landing/train_1.svg
  public/image/landing/train_2.svg
  public/image/landing/train_3.svg
  public/image/landing/workers1.svg
  public/image/landing/workers1_01.svg
  public/image/landing/workers2.svg
  public/image/landing/workers2_01.svg
  public/image/landing/workers3.svg
  public/image/landing/workers3_01.svg
  src/app/(landing)/_components/BottomSection/Illustration/Workers.tsx
  src/app/(landing)/_components/BottomSection/LandingBottomBg.tsx
  src/app/(landing)/_components/BottomSection/LandingBottomText.tsx
  src/app/(landing)/_components/BottomSection/index.tsx
  src/app/(landing)/_components/DummyHeader.tsx
  src/app/(landing)/_components/MiddleSection/LandingBox.tsx
  src/app/(landing)/_components/MiddleSection/index.tsx
  src/app/(landing)/_components/StartButton.tsx
  src/app/(landing)/_components/TopSection/Illustration/Light.tsx
  src/app/(landing)/_components/TopSection/Illustration/Runner.tsx
  src/app/(landing)/_components/TopSection/Illustration/Smoke.tsx
  src/app/(landing)/_components/TopSection/Illustration/Train.tsx
  src/app/(landing)/_components/TopSection/Illustration/index.ts
  src/app/(landing)/_components/TopSection/LandingTopBg.tsx
  src/app/(landing)/_components/TopSection/LandingTopText.tsx
  src/app/(landing)/_components/TopSection/index.tsx
  src/app/(landing)/_components/landingImageUrl.ts
  src/app/(landing)/_components/styles/boxStyle.ts
  src/app/(landing)/_components/styles/illustrationStyle.ts
  src/app/(landing)/_components/styles/motionStyle.ts
  src/app/(landing)/_components/type.ts
  src/app/page.tsx
  tailwind.config.ts
Labels: 💫feat

#134 [feat, refactor] #119 ToggleTaskDoneButton 클릭 시 데이터 변경 후 바로 화면에 반영하는 방식 변경
  src/app/(board)/article/add-article/page.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/components/task/ToggleTaskDoneButton/hooks/useToggleTaskDone.ts
  src/components/task/ToggleTaskDoneButton/index.tsx
  src/lib/apis/article/index.ts
  src/lib/apis/comment/index.ts
  src/lib/apis/group/index.ts
  src/lib/apis/task/index.ts
  src/lib/apis/taskList/index.ts
  src/lib/apis/user/index.ts
  src/lib/server/fetcher.server.ts
Labels: 💫feat, ⚒️ refactor

#140 [design, fix, feat] #139 landing: 애니메이션 속도 조절 & 이미지 무한 요청 오류 해결 & 페이지 이동 연결
  src/app/(landing)/_components/BottomSection/Illustration/Workers.tsx
  src/app/(landing)/_components/DummyHeader.tsx
  src/app/(landing)/_components/MiddleSection/LandingBox.tsx
  src/app/(landing)/_components/StartButton.tsx
  src/app/(landing)/_components/TopSection/LandingTopText.tsx
  src/app/(landing)/_components/TopSection/index.tsx
  src/app/(landing)/_components/styles/boxStyle.ts
  src/app/(landing)/_components/styles/buttonStyle.ts
  src/app/(landing)/_components/styles/motionStyle.ts
  src/app/page.tsx
Labels: 💫feat, ⚒️ fix, 🎨 design

#144 [refactor] InputTextarea: base 모드 추가 & reply 모드에 버튼 배치, onClick prop 추가
  src/components/common/Input/InputTextarea/index.tsx
Labels: ⚒️ refactor

#141 [feat] #109 TaskDetailPage: 코멘트 섹션 레이아웃 및 기능 완료
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/AutoResizeTextarea.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/EditableTaskCommentCard/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentCard/CommentMenu/CommentMenuButton.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentCard/CommentMenu/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentCard/DateInfo.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentCard/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentInput/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskDetailSection/DoneInfo.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskDetailSection/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/layout.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/(..)task/[taskid]/_components/Background.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/(..)task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/layout.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/app/layout.tsx
  src/components/common/Modal/index.tsx
  src/components/task/TaskMenu/index.tsx
  src/components/tasklist/TaskListMenu/index.tsx
  src/components/user/UserIcon.tsx
  src/components/user/WriterInfo.tsx
  src/lib/apis/comment/index.ts
  src/utils/formatElapsedTime.ts
Labels: 💫feat, 🎨 design

#147 [feat, refactor] #89 TaskListMenu: 할 일 목록 생성/수정/삭제 기능 추가 / Modal: 리퀘스트 바디 관련 상태 추가
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/EditableTaskCommentCard/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentCard/CommentMenu/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentInput/index.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/components/common/Modal/content/CreateTaskListModal/index.tsx
  src/components/common/Modal/content/EditTaskListModal/index.tsx
  src/components/common/Modal/index.tsx
  src/components/tasklist/TaskListMenu/actions/taskListActions.ts
  src/components/tasklist/TaskListMenu/index.tsx
  src/lib/apis/taskList/index.ts
  src/store/useModalStore.ts
Labels: 💫feat, ⚒️ refactor

#149 [feat, refactor] #143 TaskMenu: 할 일 삭제 기능 추가 / InputTextarea: prop 추가 및 높이 설정 방식 변경
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/AutoResizeTextarea.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/EditableTaskCommentCard.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentInput.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentInput/index.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskDetailSection/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/TaskCard/index.tsx
  src/components/common/Input/InputTextarea/index.tsx
  src/components/task/TaskMenu/actions/taskActions.ts
  src/components/task/TaskMenu/index.tsx
  src/lib/apis/task/index.ts
Labels: 💫feat, ⚒️ refactor

#151 [feat] #115 404 Not Found 페이지 디자인 및 구현
  public/image/error_404.png
  src/app/not-found.tsx
Labels: 💫feat

#152 [feat] #135 Zod 기반 유효성 검증 분리 / 컴포넌트 역할 분리 / 쿠키 설정 추가
  next.config.mjs
  package-lock.json
  package.json
  src/app/(auth)/login/_components/LoginForm/InputWithLabel.tsx
  src/app/(auth)/login/_components/LoginForm/index.tsx
  src/app/(auth)/login/type/index.ts
Labels: 💫feat, ⚒️ fix, ⚒️ refactor

#145 [feat] #120 team: TeamBanner 컴포넌트 추가 / hooks: useIsAdmin 추가 / common: Skeleton, GradientScrollable 공통 컴포넌트 추가 / constants: message 추가
  .gitignore
  package-lock.json
  package.json
  public/image/team_banner_pattern.svg
  src/app/(team)/team/[teamid]/page.tsx
  src/app/(team)/team/_components/TaskListBar/ProcessBadge.tsx
  src/app/(team)/team/_components/TaskListBar/index.tsx
  src/app/(team)/team/_components/TeamBanner/TeamMenu.tsx
  src/app/(team)/team/_components/TeamBanner/index.tsx
  src/app/(team)/team/_components/styles.ts
  src/components/common/Loading/Skeleton.tsx
  src/components/common/Scroll/GradientScrollable.tsx
  src/constants/errorMessage.ts
  src/constants/successMessage.ts
  src/hooks/useIsAdmin.ts
Labels: 💫feat

#156 [refactor, design] #150 InputTextarea: label 관련 prop 추가 및 스타일 변경
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/EditableTaskCommentCard.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/TaskCommentInput.tsx
  src/components/common/Input/InputTextarea/index.tsx
  src/components/common/Modal/content/CreateTaskModal/index.tsx
Labels: 🎨 design, ⚒️ refactor

#157 [feat, design] #155 회원가입(SignupForm): UI 레이아웃 / 유효성 검사 / API 연동 구현
  src/app/(auth)/login/_components/LoginForm/index.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/SignupForm.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/InputWithLabel.tsx
  src/components/auth/type.ts
  src/components/common/Input/InputAuth/index.tsx
  src/utils/inputValidation.ts
Labels: 💫feat, 🎨 design

#158 [feat, design] #150 할 일 생성 모달 Datepicker & Timepicker 생성
  package-lock.json
  package.json
  src/app/styles/datepicker.css
  src/app/styles/globals.css
  src/app/styles/scroll.css
  src/assets/icons/calendar_arrow.svg
  src/components/common/Datepicker/index.tsx
  src/components/common/Icons/index.tsx
  src/components/common/Input/InputTextarea/index.tsx
  src/components/common/Modal/content/CreateTaskModal/StartDateTimeSection/index.tsx
  src/components/common/Modal/content/CreateTaskModal/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Timepicker/index.tsx
  src/components/tasklist/TaskListMenu/index.tsx
Labels: 💫feat, 🎨 design

#159 [feat, refactor, design] #150 할 일 생성 모달 반복 설정 섹션 & API 연결
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskDetailSection/index.tsx
  src/app/(team)/team/[teamid]/tasklist/@sidePage/(..)task/[taskid]/page.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/CreateTaskButton/actions/createTaskAction.ts
  src/app/(team)/team/[teamid]/tasklist/_components/CreateTaskButton/index.tsx
  src/app/(team)/team/[teamid]/tasklist/page.tsx
  src/components/common/Input/InputTextarea/index.tsx
  src/components/common/Modal/content/CreateTaskModal/hooks/useTaskFormValidation.ts
  src/components/common/Modal/content/CreateTaskModal/index.tsx
  src/components/task-modal/RecurringSection/FrequencyTypeSelector.tsx
  src/components/task-modal/RecurringSection/MonthDaySelector.tsx
  src/components/task-modal/RecurringSection/WeekDaysSelector.tsx
  src/components/task-modal/RecurringSection/index.tsx
  src/components/task-modal/StartDateTimeSection/index.tsx
  src/components/tasklist/TaskListMenu/index.tsx
  src/lib/apis/task/index.ts
Labels: 💫feat, 🎨 design, ⚒️ refactor

#160 [feat] #137 team: 할 일 목록: TaskListBarList / 멤버: MemberList 컴포넌트 구현
  src/app/(team)/team/[teamid]/page.tsx
  src/app/(team)/team/_components/MemberList/BreakEmail.tsx
  src/app/(team)/team/_components/MemberList/MemberCard.tsx
  src/app/(team)/team/_components/MemberList/index.tsx
  src/app/(team)/team/_components/MemberList/styles.ts
  src/app/(team)/team/_components/TaskListBar/ProcessBadge.tsx
  src/app/(team)/team/_components/TaskListBar/index.tsx
  src/app/(team)/team/_components/TaskListBarList/Pagination.tsx
  src/app/(team)/team/_components/TaskListBarList/ProcessBadge.tsx
  src/app/(team)/team/_components/TaskListBarList/TaskListBar.tsx
  src/app/(team)/team/_components/TaskListBarList/TaskListDropdownMenu.tsx
  src/app/(team)/team/_components/TaskListBarList/index.tsx
  src/app/(team)/team/_components/TaskListBarList/styles.ts
  src/app/(team)/team/_components/TeamBanner/TeamDropdownMenu.tsx
  src/app/(team)/team/_components/TeamBanner/index.tsx
  src/app/(team)/team/_components/TeamBanner/styles.ts
  src/app/(team)/team/_components/styles.ts
  src/components/common/Dropdown/DropDownTrigger.tsx
  src/components/common/Scroll/GradientScrollable.tsx
  src/components/user/UserIcon.tsx
Labels: 💫feat

#165 [feat, refactor] #89 TaskListPage: 특정 날짜의 할 일 목록 표시 기능 추가 / 할 일 수정 모달 추가
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskDetailSection/index.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/CalendarButton.tsx
  src/app/(team)/team/[teamid]/tasklist/_components/TaskListSection/TaskCard/index.tsx
  src/app/styles/datepicker.css
  src/components/common/Datepicker/index.tsx
  src/components/common/Modal/content/CreateTaskModal/hooks/useCreateTaskFormValidation.ts
  src/components/common/Modal/content/CreateTaskModal/index.tsx
  src/components/common/Modal/content/EditTaskModal/hooks/useEditTaskFormValidation.ts
  src/components/common/Modal/content/EditTaskModal/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Timepicker/index.tsx
  src/components/task-modal/StartDateTimeSection/index.tsx
  src/components/task/TaskMenu/index.tsx
  src/components/user/UserIcon.tsx
Labels: 💫feat, ⚒️ refactor

#168 [feat, design] #164 ResetPasswordPage, ResetPasswordForm: 비밀번호 재설정 폼 레이아웃 / 입력 유효성 구현
  src/app/(auth)/reset-password/ResetPasswordForm.tsx
  src/app/(auth)/reset-password/page.tsx
  src/components/auth/InputWithLabel.tsx
  src/components/auth/type.ts
Labels: 💫feat, 🎨 design

#171 [feat] #153 마이히스토리페이지 생성
  src/app/(user)/myhistory/_components/MyHistorySection/HistoryCard/HistoryCard.tsx
  src/app/(user)/myhistory/_components/MyHistorySection/HistoryCard/index.tsx
  src/app/(user)/myhistory/_components/MyHistorySection/index.tsx
  src/app/(user)/myhistory/page.tsx
  src/lib/apis/user/index.ts
  src/utils/groupByDate.ts
Labels: 💫feat

#169 [feat, design] #166 ArticleDetailPage: 아티클 상세 섹션 레이아웃 & 유저 메뉴 기능 추가 / BoardsPage: 레이아웃 수정
  src/app/(board)/article/[articleid]/ArticleCommentSection/index.tsx
  src/app/(board)/article/[articleid]/ArticleDetailSection/CommentInfo.tsx
  src/app/(board)/article/[articleid]/ArticleDetailSection/DateInfo.tsx
  src/app/(board)/article/[articleid]/ArticleDetailSection/ToggleLikeButton.tsx
  src/app/(board)/article/[articleid]/ArticleDetailSection/index.tsx
  src/app/(board)/article/[articleid]/page.tsx
  src/app/(board)/boards/_components/BestPostCard.tsx
  src/app/(board)/boards/_components/BestPostList.tsx
  src/app/(board)/boards/_components/BoardContent.tsx
  src/app/(board)/boards/_components/PostCard.tsx
  src/app/(board)/boards/_components/PostList.tsx
  src/app/(board)/boards/_components/SearchInput.tsx
  src/app/(board)/boards/_components/SortDropdown.tsx
  src/app/(board)/boards/_components/WriteButton.tsx
  src/app/(board)/boards/_hooks/usePosts.ts
  src/app/(board)/boards/page.tsx
  src/assets/icons/best_badge.svg
  src/assets/icons/heart_empty.svg
  src/assets/icons/heart_full.svg
  src/components/article/ArticleMenu/ArticleMenuButton.tsx
  src/components/article/ArticleMenu/actions/articleActions.ts
  src/components/article/ArticleMenu/index.tsx
  src/components/common/Icons/index.tsx
  src/hooks/useIsWriter.ts
  src/lib/apis/article/index.ts
Labels: 💫feat, 🎨 design

#172 [feat, refactor] #137 team: 모달 연결 및 진행률 표시 & ReportBanner 컴포넌트 구현 / UserIcon: size 관리 방식 변경
  public/image/team_done.svg
  src/app/(team)/team/[teamid]/page.tsx
  src/app/(team)/team/_components/AddButton/handleInvite.ts
  src/app/(team)/team/_components/AddButton/index.tsx
  src/app/(team)/team/_components/MemberList/MemberCard.tsx
  src/app/(team)/team/_components/MemberList/MemberMenu.tsx
  src/app/(team)/team/_components/MemberList/styles.ts
  src/app/(team)/team/_components/ReportBanner/ReportCard.tsx
  src/app/(team)/team/_components/ReportBanner/index.tsx
  src/app/(team)/team/_components/ReportBanner/styles.ts
  src/app/(team)/team/_components/TaskListBarList/CircularProgress.tsx
  src/app/(team)/team/_components/TaskListBarList/ProcessBadge.tsx
  src/app/(team)/team/_components/TaskListBarList/ProgressBadge.tsx
  src/app/(team)/team/_components/TaskListBarList/TaskListBar.tsx
  src/app/(team)/team/_components/TaskListBarList/index.tsx
  src/app/(team)/team/_components/TaskListBarList/styles.ts
  src/app/(team)/team/_components/TeamBanner/TeamMenu.tsx
  src/app/(team)/team/_components/TeamBanner/index.tsx
  src/app/(team)/team/_components/styles.ts
  src/app/styles/dropdown.ts
  src/app/styles/globals.css
  src/components/common/Dropdown/DropDownItem.tsx
  src/components/common/Modal/content/MemberProfileModal/index.tsx
  src/components/common/Modal/content/TeamMemberProfileModal/index.tsx
  src/components/tasklist/TaskListMenu/index.tsx
  src/components/user/UserIcon.tsx
  src/constants/errorMessage.ts
  src/constants/messages.ts
  src/constants/successMessage.ts
  src/utils/calculateProgress.ts
  src/utils/calculateTaskListProgress.ts
Labels: 💫feat, ⚒️ refactor

#174 [feat] #173 no team: UI 및 라우팅 연결
  public/image/no_team.png
  src/app/(team)/no-team/page.tsx
Labels: 💫feat

#182 [feat, refactor] #153 my history page
  src/app/(user)/myhistory/page.tsx
  src/utils/groupByDate.ts
Labels: 💫feat, ⚒️ fix, ⚒️ refactor

#175 [feat, design] #166 ArticleDetailPage: 아티클 코멘트 섹션 레이아웃 및 기능 완료
  src/app/(board)/article/[articleid]/ArticleCommentSection/ArticleCommentInput.tsx
  src/app/(board)/article/[articleid]/ArticleCommentSection/ArticleCommentList/ArticleCommentCard/CommentMenu/CommentMenuButton.tsx
  src/app/(board)/article/[articleid]/ArticleCommentSection/ArticleCommentList/ArticleCommentCard/CommentMenu/index.tsx
  src/app/(board)/article/[articleid]/ArticleCommentSection/ArticleCommentList/ArticleCommentCard/DateInfo.tsx
  src/app/(board)/article/[articleid]/ArticleCommentSection/ArticleCommentList/ArticleCommentCard/index.tsx
  src/app/(board)/article/[articleid]/ArticleCommentSection/ArticleCommentList/EditableArticleCommentCard.tsx
  src/app/(board)/article/[articleid]/ArticleCommentSection/ArticleCommentList/index.tsx
  src/app/(board)/article/[articleid]/ArticleCommentSection/index.tsx
  src/app/(board)/article/[articleid]/page.tsx
  src/app/(team)/team/[teamid]/task/[taskid]/_components/TaskCommentSection/EditableTaskCommentCard.tsx
  src/app/dev-login/_components/LoginButton.tsx
  src/components/common/Loading/Spinner.tsx
  src/components/common/Modal/index.tsx
  src/hooks/useIntersection.ts
  src/lib/apis/articleComment/index.ts
Labels: 💫feat, 🎨 design

#184 [fix] #183 모달 오픈 시 스크롤바 밀림 이슈 처리 방식 gutter -> padding 변경
  src/app/styles/dropdown.ts
  src/app/styles/globals.css
  src/hooks/useLockBackgroundScroll.ts
Labels: ⚒️ fix

#188 [feat] #142 팀 생성 페이지 / 팀 수정 페이지
  src/app/(team)/_components/TeamProfileForm/index.tsx
  src/app/(team)/add-team/page.tsx
  src/app/(team)/team/[teamid]/edit/page.tsx
  src/hooks/useGroupQueries.ts
Labels: 💫feat

#189 [refactor] #187 landing: 모바일 애니메이션 아이템 사라짐 fix & 이미지 파일 정리
  public/image/landing/bg_bottom_l.png
  public/image/landing/bg_bottom_m.png
  public/image/landing/bg_bottom_s.png
  public/image/landing/bg_pattern_top_l.png
  public/image/landing/bg_pattern_top_m.png
  public/image/landing/bg_pattern_top_s.png
  public/image/landing/icon_box_check.svg
  public/image/landing/icon_box_folder.svg
  public/image/landing/icon_box_message.svg
  public/image/landing/il_light_l.png
  public/image/landing/il_light_m.png
  public/image/landing/il_light_s.png
  public/image/landing/il_runner.svg
  public/image/landing/il_smoke.svg
  public/image/landing/il_train_1.svg
  public/image/landing/il_train_2.svg
  public/image/landing/il_train_3.svg
  public/image/landing/il_workers1.svg
  public/image/landing/il_workers1_01.svg
  public/image/landing/il_workers2.svg
  public/image/landing/il_workers2_01.svg
  public/image/landing/il_workers3.svg
  public/image/landing/il_workers3_01.svg
  public/image/landing/landing_bottom_bg_m_01.png
  public/image/landing/landing_icon_check.png
  public/image/landing/landing_icon_folder.png
  public/image/landing/landing_icon_message.png
  public/image/landing/landing_light.png
  public/image/landing/landing_light_01.png
  public/image/landing/landing_light_l.png
  public/image/landing/landing_light_m.png
  public/image/landing/landing_light_s.png
  public/image/landing/landing_light_s_01.png
  public/image/landing/landing_mockup_invitation.png
  public/image/landing/landing_mockup_reply.png
  public/image/landing/landing_mockup_team.png
  public/image/landing/landing_top_bg_l.png
  public/image/landing/landing_top_bg_m.png
  public/image/landing/landing_top_bg_s.png
  public/image/landing/mockup_invitation.png
  public/image/landing/mockup_reply.png
  public/image/landing/mockup_team.png
  src/app/(landing)/_components/BottomSection/Illustration/Workers.tsx
  src/app/(landing)/_components/BottomSection/LandingBottomBg.tsx
  src/app/(landing)/_components/BottomSection/index.tsx
  src/app/(landing)/_components/MiddleSection/index.tsx
  src/app/(landing)/_components/TopSection/Illustration/Light.tsx
  src/app/(landing)/_components/TopSection/Illustration/Runner.tsx
  src/app/(landing)/_components/TopSection/Illustration/Smoke.tsx
  src/app/(landing)/_components/TopSection/Illustration/Train.tsx
  src/app/(landing)/_components/TopSection/LandingTopBg.tsx
  src/app/(landing)/_components/TopSection/index.tsx
  src/app/(landing)/_components/styles/motionStyle.ts
Labels: ⚒️ refactor

#191 [feat, refactor] #185 Datepicker: 종료일을 선택할 수 있도록 확장 / MyHistoryPage: CustomDatePicker 컴포넌트 적용 & Data Fetching 방식 변경
  src/app/(team)/team/[teamid]/tasklist/_components/DateMenu/CalendarButton.tsx
  src/app/(user)/myhistory/_components/MyHistoryPageContent/CustomDateSelector.tsx
  src/app/(user)/myhistory/_components/MyHistoryPageContent/MyHistorySection/HistoryCard.tsx
  src/app/(user)/myhistory/_components/MyHistoryPageContent/MyHistorySection/index.tsx
  src/app/(user)/myhistory/_components/MyHistoryPageContent/index.tsx
  src/app/(user)/myhistory/_components/MyHistorySection/HistoryCard/index.tsx
  src/app/(user)/myhistory/page.tsx
  src/components/common/Datepicker/index.tsx
  src/components/task-modal/StartDateTimeSection/index.tsx
Labels: 💫feat, ⚒️ refactor

#193 [feat] #167 계정 설정 페이지
  package-lock.json
  package.json
  public/image/secession_icon.svg
  src/app/(user)/mypage/_components/AccountInfoSection.tsx
  src/app/(user)/mypage/_components/AccountUpdateButton.tsx
  src/app/(user)/mypage/_components/PasswordChangeSection.tsx
  src/app/(user)/mypage/_components/ProfileImageUploader.tsx
  src/app/(user)/mypage/_components/SecessionButton.tsx
  src/app/(user)/mypage/_components/schemas/passwordSchema.ts
  src/app/(user)/mypage/_hooks/useAccountInfoStore.ts
  src/app/(user)/mypage/_hooks/usePasswordChange.ts
  src/app/(user)/mypage/_hooks/usePasswordStore.ts
  src/app/(user)/mypage/_hooks/useProfileImageStore.ts
  src/app/(user)/mypage/page.tsx
  src/components/common/Input/InputAuth/index.tsx
  src/components/common/Modal/content/UpdatePasswordModal/index.tsx
  src/lib/apis/user/type.ts
Labels: 💫feat

#201 [design] #173 no team: 버튼 높이 및 여백 조정
  src/app/(team)/no-team/page.tsx
Labels: 🎨 design

#200 [feat, refactor] #190 팀 참여 페이지 작성 / 팀 생성, 수정 페이지 리팩토링
  public/image/default_team_img.png
  src/app/(team)/_components/JoinTeamForm/index.tsx
  src/app/(team)/_components/TeamProfileForm/index.tsx
  src/app/(team)/join-team/page.tsx
  src/app/(team)/team/[teamid]/edit/page.tsx
  src/components/common/Header/TeamMenu.tsx
  src/hooks/useGroupQueries.ts
  src/utils/errorMap.ts
Labels: 💫feat, ⚒️ refactor

#203 [feat] #199 #205 인증 상태에 따른 리다이렉션 / 로그인 페이지 리다이렉트 / 로그인, 회원가입 페이지 반응형
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/_components/LoginForm/OpenPasswordResetModal.tsx
  src/app/(auth)/login/_components/LoginForm/index.tsx
  src/app/(auth)/login/_components/NavigateToSignUp/index.tsx
  src/app/(auth)/login/_components/SocialLogin/index.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/SignupForm.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(board)/layout.tsx
  src/app/(team)/layout.tsx
  src/app/(user)/layout.tsx
Labels: 💫feat

#209 [feat] #206 비밀번호 재설정 페이지 구현 / 요청에 따른 응답 처리 분기 / 코드 리뷰 반영
  src/app/(auth)/login/_components/LoginForm/OpenPasswordResetModal.tsx
  src/app/(auth)/reset-password/ResetPasswordForm.tsx
  src/app/(auth)/reset-password/page.tsx
  src/components/common/Modal/index.tsx
  src/lib/apis/user/index.ts
Labels: 💫feat

#210 [refactor] #186 모바일 환경 스크롤 UX 개선 목적 GradientScrollable 반응형 리팩토링
  src/app/(team)/team/_components/TeamBanner/styles.ts
  src/components/common/Scroll/GradientScrollable.tsx
Labels: ⚒️ refactor

#213 [refactor] 헤더 컴포넌트 / 기타 리팩토링
  src/app/(team)/_components/TeamProfileForm/index.tsx
  src/app/(user)/mypage/_components/AccountUpdateButton.tsx
  src/components/common/Header/SideMenu.tsx
  src/components/common/Header/TeamMenu.tsx
  src/components/common/Header/index.tsx
  src/hooks/useGroupQueries.ts
  src/hooks/useMemberships.ts
Labels: ⚒️ refactor
